sudo: required
language: node_js
node_js:
  - "6"
before_install:
  - "npm config set spin false"
  - "npm install -g typescript@2.0.3"
install:
  - "npm install"
  - "npm link typescript"
  - "npm run build"